### ISSUE TITLE
Unable to attach or mount volumes: unmounted volumes=[mypvc2], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition

### ISSUE THREAD

**Issue by thelman** [cubefs/cubefs-csi#108]
I'm using the following versions:

    server: cubefs/cfs-server:v3.3.2
    csi-provisioner: registry.k8s.io/sig-storage/csi-provisioner:v2.2.2
    csi-attacher: registry.k8s.io/sig-storage/csi-attacher:v3.4.0
    csi-resizer: registry.k8s.io/sig-storage/csi-resizer:v1.3.0
    cfs-driver: cubefs/cfs-csi-driver:v3.3.2

I have the following configuration for:

storage:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cfs-sc
provisioner: csi.cubefs.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  # Resource manager IP address or URL
  masterAddr: "master.cubefs.ejemplo.page"
  # Owner name as authentication
  owner: "csiuser"
  logLevel: "debug"
```
pvc:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cubefs-pvc2
  namespace: cubefs
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: cfs-sc
```
deploy
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfs-csi-demo2
  namespace: cubefs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfs-csi-demo-pod
  template:
    metadata:
      labels:
        app: cfs-csi-demo-pod
    spec:
      nodeSelector:
        "component.cubefs.io/datanode": "enabled"
      tolerations:
        - effect: NoSchedule
          key: artificial-intelligence
          operator: Equal
          value: dedicated
      containers:
        - name: cfs-csi-demo
          image: nginx:1.17.9
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: mypvc2
      volumes:
        - name: mypvc2
          persistentVolumeClaim:
            claimName: cubefs-pvc2
```
   
The pod stays in Pending status for about 10 to 20 minutes with the following error:

MountVolume.MountDevice failed for volume "pvc-6d8d2ffa-fb8b-43bf-ae4f-bb1c31588c15" : rpc error: code = DeadlineExceeded desc = context deadline exceeded

Unable to attach or mount volumes: unmounted volumes=[mypvc2], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition

There are no errors in the /cfs/logs of the cfs-driver, only the kubelet error appears in the events of the namespace.

After 10 or 20 minutes, the pod starts correctly
